In [8]:
#Loading the main dataset
import duckdb

con = duckdb.connect()

df = con.sql("""
SELECT *
FROM read_csv_auto(
    'C:/Users/Lenovo/supply-chain-capstone-project/data/raw/DataCoSupplyChainDataset.csv',
    ignore_errors=true,
    all_varchar=true
)
LIMIT 10
""").df()

df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.25,314.6400146,Advance shipping,0,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,DEBIT,3,4,22.86000061,304.8099976,Advance shipping,0,73,Sporting Goods,Los Angeles,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
2,PAYMENT,2,4,134.2100067,298.25,Advance shipping,0,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
3,TRANSFER,6,4,18.57999992,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
4,DEBIT,2,1,95.18000031,288.4200134,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
5,TRANSFER,2,1,68.43000031,285.1400146,Late delivery,1,73,Sporting Goods,Miami,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
6,CASH,3,2,133.7200012,278.5899963,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
7,CASH,2,1,132.1499939,275.3099976,Late delivery,1,73,Sporting Goods,San Ramon,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class
8,DEBIT,2,1,24.57999992,245.8099976,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 8:15,First Class
9,TRANSFER,2,1,16.38999939,327.75,Late delivery,1,73,Sporting Goods,Peabody,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 7:54,First Class

In [10]:
#loading the description dataset
desc_df = con.sql("""
SELECT *
FROM read_csv_auto(
    'C:/Users/Lenovo/supply-chain-capstone-project/data/raw/DescriptionDataCoSupplyChain.csv',
    ignore_errors=true,
    all_varchar=true
)
LIMIT 10
""").df()

desc_df

,FIELDS,DESCRIPTION
0,Type,: Type of transaction made
1,Days for shipping (real),: Actual shipping days of the purchased product
2,Days for shipment (scheduled),: Days of scheduled delivery of the purchased...
3,Benefit per order,: Earnings per order placed
4,Sales per customer,: Total sales per customer made per customer
5,Delivery Status,: Delivery status of orders: Advance shipping...
6,Late_delivery_risk,: Categorical variable that indicates if send...
7,Category Id,: Product category code
8,Category Name,: Description of the product category
9,Customer City,: City where the customer made the purchase

In [12]:
#Loading the logs dataset
logs_df = con.sql("""
SELECT *
FROM read_csv_auto(
    'C:/Users/Lenovo/supply-chain-capstone-project/data/raw/tokenized_access_logs.csv',
    ignore_errors=true,
    all_varchar=true
)
LIMIT 1000
""").df()

logs_df

,Product,Category,Date,Month,Hour,Department,ip,url
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,Sep,6,fitness,37.97.182.65,/department/fitness/category/baseball%20&%20so...
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,Sep,6,fan shop,206.56.112.1,/department/fan%20shop/category/hunting%20&%20...
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,Sep,6,apparel,215.143.180.0,/department/apparel/category/featured%20shops/...
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,Sep,6,footwear,206.56.112.1,/department/footwear/category/electronics/prod...
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,Sep,6,fan shop,136.108.56.242,/department/fan%20shop/category/water%20sports...
...,...,...,...,...,...,...,...,...
995,Under Armour Hustle Storm Medium Duffle Bag,fitness accessories,9/1/2017 12:32,Sep,12,footwear,219.252.175.214,/department/footwear/category/fitness%20access...
996,Perfect Fitness Perfect Rip Deck,cleats,9/1/2017 12:32,Sep,12,apparel,149.95.217.202,/department/apparel/category/cleats/product/Pe...
997,Under Armour Women's Micro G Skulpt Running S,boxing & mma,9/1/2017 12:32,Sep,12,footwear,197.221.161.51,/department/footwear/category/boxing%20&%20mma...
998,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 12:32,Sep,12,apparel,154.237.22.202,/department/apparel/category/featured%20shops/...
999,Nike Men's Comfort 2 Slide,tennis & racquet,9/1/2017 12:32,Sep,12,fitness,37.97.182.65,/department/fitness/category/tennis%20&%20racq...