In [ ]:
RAW_SUPPLY_CHAIN_CSV = '../data/raw/DataCoSupplyChainDataset.csv'
RAW_ACCESS_LOGS_CSV = '../data/raw/tokenized_access_logs.csv'
CLEAN_OUTPUT_DIR= '../data/clean'

In [42]:
from pathlib import Path
import duckdb

con = duckdb.connect()

df = con.sql(f"""
SELECT *
FROM read_csv_auto(
    '{RAW_SUPPLY_CHAIN_CSV}',
    ignore_errors=true,
    all_varchar=true
)
LIMIT 10
""").df()

df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.25,314.6400146,Advance shipping,0,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,DEBIT,3,4,22.86000061,304.8099976,Advance shipping,0,73,Sporting Goods,Los Angeles,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
2,PAYMENT,2,4,134.2100067,298.25,Advance shipping,0,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
3,TRANSFER,6,4,18.57999992,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
4,DEBIT,2,1,95.18000031,288.4200134,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
5,TRANSFER,2,1,68.43000031,285.1400146,Late delivery,1,73,Sporting Goods,Miami,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
6,CASH,3,2,133.7200012,278.5899963,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
7,CASH,2,1,132.1499939,275.3099976,Late delivery,1,73,Sporting Goods,San Ramon,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class
8,DEBIT,2,1,24.57999992,245.8099976,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 8:15,First Class
9,TRANSFER,2,1,16.38999939,327.75,Late delivery,1,73,Sporting Goods,Peabody,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 7:54,First Class

In [43]:
#Loading the main dataset
import duckdb

con = duckdb.connect()

df = con.sql(f"""
SELECT *
FROM read_csv_auto(
    '{RAW_SUPPLY_CHAIN_CSV}',
    ignore_errors=true,
    all_varchar=true
)
LIMIT 10
""").df()

df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.25,314.6400146,Advance shipping,0,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,DEBIT,3,4,22.86000061,304.8099976,Advance shipping,0,73,Sporting Goods,Los Angeles,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
2,PAYMENT,2,4,134.2100067,298.25,Advance shipping,0,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
3,TRANSFER,6,4,18.57999992,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
4,DEBIT,2,1,95.18000031,288.4200134,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
5,TRANSFER,2,1,68.43000031,285.1400146,Late delivery,1,73,Sporting Goods,Miami,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
6,CASH,3,2,133.7200012,278.5899963,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
7,CASH,2,1,132.1499939,275.3099976,Late delivery,1,73,Sporting Goods,San Ramon,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class
8,DEBIT,2,1,24.57999992,245.8099976,Late delivery,1,73,Sporting Goods,Caguas,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 8:15,First Class
9,TRANSFER,2,1,16.38999939,327.75,Late delivery,1,73,Sporting Goods,Peabody,...,None,1360,73,None,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 7:54,First Class

In [44]:
con.sql(f"""
SELECT COUNT(*) AS total_rows
FROM read_csv_auto(
    '{RAW_SUPPLY_CHAIN_CSV}',
    ignore_errors=true
)
""").show()

┌────────────┐
│ total_rows │
│   int64    │
├────────────┤
│     180519 │
└────────────┘

In [45]:
#Loading the logs dataset
logs_df = con.sql(f"""
SELECT *
FROM read_csv_auto(
    '{RAW_ACCESS_LOGS_CSV}',
    ignore_errors=true,
    all_varchar=true
)
LIMIT 1000
""").df()

logs_df

,Product,Category,Date,Month,Hour,Department,ip,url
0,adidas Brazuca 2017 Official Match Ball,baseball & softball,9/1/2017 6:00,Sep,6,fitness,37.97.182.65,/department/fitness/category/baseball%20&%20so...
1,The North Face Women's Recon Backpack,hunting & shooting,9/1/2017 6:00,Sep,6,fan shop,206.56.112.1,/department/fan%20shop/category/hunting%20&%20...
2,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 6:00,Sep,6,apparel,215.143.180.0,/department/apparel/category/featured%20shops/...
3,Under Armour Men's Compression EV SL Slide,electronics,9/1/2017 6:00,Sep,6,footwear,206.56.112.1,/department/footwear/category/electronics/prod...
4,Pelican Sunstream 100 Kayak,water sports,9/1/2017 6:01,Sep,6,fan shop,136.108.56.242,/department/fan%20shop/category/water%20sports...
...,...,...,...,...,...,...,...,...
995,Under Armour Hustle Storm Medium Duffle Bag,fitness accessories,9/1/2017 12:32,Sep,12,footwear,219.252.175.214,/department/footwear/category/fitness%20access...
996,Perfect Fitness Perfect Rip Deck,cleats,9/1/2017 12:32,Sep,12,apparel,149.95.217.202,/department/apparel/category/cleats/product/Pe...
997,Under Armour Women's Micro G Skulpt Running S,boxing & mma,9/1/2017 12:32,Sep,12,footwear,197.221.161.51,/department/footwear/category/boxing%20&%20mma...
998,adidas Kids' RG III Mid Football Cleat,featured shops,9/1/2017 12:32,Sep,12,apparel,154.237.22.202,/department/apparel/category/featured%20shops/...
999,Nike Men's Comfort 2 Slide,tennis & racquet,9/1/2017 12:32,Sep,12,fitness,37.97.182.65,/department/fitness/category/tennis%20&%20racq...

In [47]:
clean_df = con.sql(f"""
SELECT 

    CAST("Order Id" AS VARCHAR) AS order_id,
    CAST("Customer Id" AS VARCHAR) AS customer_id,

    LOWER(TRIM("Product Name")) AS product_name,
    LOWER(TRIM("Category Name")) AS category,
    "Department Name" AS department,

    "Product Price",
    "Product Image" AS product_image,

    "Order Region",
    "Market",
    "Order Status",

    "Shipping Mode",

    CAST("Days for shipping (real)" AS DOUBLE) AS actual_days,
    CAST("Days for shipment (scheduled)" AS DOUBLE) AS scheduled_days,

    COALESCE(CAST("Sales" AS DOUBLE), 0) AS sales,
    CAST("Order Item Quantity" AS INTEGER) AS quantity,
    CAST("Order Profit Per Order" AS DOUBLE) AS profit,

    "Latitude",
    "Longitude",

    (CAST("Days for shipping (real)" AS DOUBLE) 
     - CAST("Days for shipment (scheduled)" AS DOUBLE)) AS delay

FROM read_csv_auto(
    '{RAW_SUPPLY_CHAIN_CSV}',
    ignore_errors=true
)
""").df()

In [48]:
#creating demand features from logs dataset
demand_df = con.sql(f"""
SELECT 
    LOWER(TRIM(Product)) AS product_name,
    COUNT(*) AS view_count,
    COUNT(DISTINCT ip) AS unique_users,
    MODE() WITHIN GROUP (ORDER BY Month) AS peak_month,
    MODE() WITHIN GROUP (ORDER BY Hour) AS peak_hour
FROM read_csv_auto(
    '{RAW_ACCESS_LOGS_CSV}',
    ignore_errors=true
)
GROUP BY product_name
""").df()

In [49]:
merged_df = clean_df.merge(
    demand_df,
    on="product_name",
    how="left"
)

merged_df["view_count"] = merged_df["view_count"].fillna(0)
merged_df["unique_users"] = merged_df["unique_users"].fillna(0)

merged_df.head(50)

,order_id,customer_id,product_name,category,department,Product Price,product_image,Order Region,Market,Order Status,...,sales,quantity,profit,Latitude,Longitude,delay,view_count,unique_users,peak_month,peak_hour
0,77202,20755,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Southeast Asia,Pacific Asia,COMPLETE,...,327.750000,1,91.250000,18.251453,-66.037056,-1.0,0.0,0.0,NaN,NaN
1,75939,19492,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,PENDING,...,327.750000,1,-249.089996,18.279451,-66.037064,1.0,0.0,0.0,NaN,NaN
2,75938,19491,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,CLOSED,...,327.750000,1,-247.779999,37.292233,-121.881279,0.0,0.0,0.0,NaN,NaN
3,75937,19490,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,COMPLETE,...,327.750000,1,22.860001,34.125946,-118.291016,-1.0,0.0,0.0,NaN,NaN
4,75936,19489,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,134.210007,18.253769,-66.037048,-2.0,0.0,0.0,NaN,NaN
5,75935,19488,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,CANCELED,...,327.750000,1,18.580000,43.013969,-78.879066,2.0,0.0,0.0,NaN,NaN
6,75934,19487,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,COMPLETE,...,327.750000,1,95.180000,18.242538,-66.037056,1.0,0.0,0.0,NaN,NaN
7,75933,19486,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,PROCESSING,...,327.750000,1,68.430000,25.928869,-80.162872,1.0,0.0,0.0,NaN,NaN
8,75932,19485,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,CLOSED,...,327.750000,1,133.720001,18.233223,-66.037056,1.0,0.0,0.0,NaN,NaN
9,75931,19484,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,CLOSED,...,327.750000,1,132.149994,37.773991,-121.966629,1.0,0.0,0.0,NaN,NaN
10,75930,19483,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,SUSPECTED_FRAUD,...,327.750000,1,130.580002,18.282845,-66.037056,4.0,0.0,0.0,NaN,NaN
11,75929,19482,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Southeast Asia,Pacific Asia,PENDING,...,327.750000,1,45.689999,40.654865,-73.587074,3.0,0.0,0.0,NaN,NaN
12,75928,19481,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Southeast Asia,Pacific Asia,PENDING,...,327.750000,1,21.760000,36.676338,-121.656517,2.0,0.0,0.0,NaN,NaN
13,75927,19480,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,COMPLETE,...,327.750000,1,24.580000,18.278439,-66.037056,1.0,0.0,0.0,NaN,NaN
14,75926,19479,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,PROCESSING,...,327.750000,1,16.389999,42.526276,-70.927032,1.0,0.0,0.0,NaN,NaN
15,75925,19478,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,COMPLETE,...,327.750000,1,-259.579987,18.284050,-66.037056,1.0,0.0,0.0,NaN,NaN
16,75924,19477,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,-246.360001,18.395790,-65.872887,3.0,0.0,0.0,NaN,NaN
17,75923,19476,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,CLOSED,...,327.750000,1,23.840000,33.898693,-118.174560,1.0,0.0,0.0,NaN,NaN
18,75922,19475,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,COMPLETE,...,327.750000,1,102.260002,18.233778,-66.037064,1.0,0.0,0.0,NaN,NaN
19,75921,19474,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,87.180000,42.048306,-87.961342,0.0,0.0,0.0,NaN,NaN
20,75920,19473,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,PROCESSING,...,327.750000,1,154.860001,33.782452,-118.192245,0.0,0.0,0.0,NaN,NaN
21,75919,19472,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,PENDING,...,327.750000,1,82.300003,18.283377,-66.037056,1.0,0.0,0.0,NaN,NaN
22,75918,19471,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,PENDING,...,327.750000,1,22.370001,38.611774,-121.282867,2.0,0.0,0.0,NaN,NaN
23,75917,19470,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,CANCELED,...,327.750000,1,17.700001,18.207336,-66.037056,1.0,0.0,0.0,NaN,NaN
24,75916,19469,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,SUSPECTED_FRAUD,...,327.750000,1,90.279999,45.788311,-108.559410,0.0,0.0,0.0,NaN,NaN
25,75915,19468,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,COMPLETE,...,327.750000,1,131.169998,18.261633,-66.037056,4.0,0.0,0.0,NaN,NaN
26,75914,19467,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,PENDING,...,327.750000,1,90.540001,41.235455,-75.869858,3.0,0.0,0.0,NaN,NaN
27,75913,19466,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,82.589996,18.270224,-66.037064,0.0,0.0,0.0,NaN,NaN
28,75912,19465,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,COMPLETE,...,327.750000,1,-17.139999,41.868862,-84.573654,-1.0,0.0,0.0,NaN,NaN
29,75911,19464,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,PROCESSING,...,327.750000,1,23.650000,33.909424,-118.125359,-2.0,0.0,0.0,NaN,NaN
30,75910,19463,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,ON_HOLD,...,327.750000,1,73.419998,18.275261,-66.037064,2.0,0.0,0.0,NaN,NaN
31,75909,19462,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,COMPLETE,...,327.750000,1,113.070000,41.865440,-88.109901,1.0,0.0,0.0,NaN,NaN
32,75908,19461,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,24.580000,18.287136,-66.037056,0.0,0.0,0.0,NaN,NaN
33,75907,19460,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,COMPLETE,...,327.750000,1,-97.339996,42.391102,-83.131218,1.0,0.0,0.0,NaN,NaN
34,75906,19459,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,-425.579987,32.865395,-96.868584,1.0,0.0,0.0,NaN,NaN
35,75905,19458,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Southeast Asia,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,152.600006,18.240742,-66.037056,1.0,0.0,0.0,NaN,NaN
36,75904,19457,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,CLOSED,...,327.750000,1,151.029999,40.031719,-76.877098,1.0,0.0,0.0,NaN,NaN
37,75903,19456,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,COMPLETE,...,327.750000,1,62.270000,32.810108,-96.686493,1.0,0.0,0.0,NaN,NaN
38,75902,19455,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,COMPLETE,...,327.750000,1,35.000000,18.286049,-66.037056,1.0,0.0,0.0,NaN,NaN
39,75901,19454,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,CANCELED,...,327.750000,1,57.299999,39.681881,-75.644211,1.0,0.0,0.0,NaN,NaN
40,75900,19453,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Southeast Asia,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,143.160004,34.158939,-118.180939,1.0,0.0,0.0,NaN,NaN
41,75899,19452,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Southeast Asia,Pacific Asia,COMPLETE,...,327.750000,1,135.690002,18.282946,-66.037064,1.0,0.0,0.0,NaN,NaN
42,75898,19451,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Southeast Asia,Pacific Asia,CLOSED,...,327.750000,1,132.669998,33.816326,-84.445503,0.0,0.0,0.0,NaN,NaN
43,75897,19450,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Southeast Asia,Pacific Asia,PENDING_PAYMENT,...,327.750000,1,119.760002,18.241039,-66.037064,-1.0,0.0,0.0,NaN,NaN
44,75896,19449,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Oceania,Pacific Asia,COMPLETE,...,327.750000,1,31.480000,37.490276,-121.927109,-2.0,0.0,0.0,NaN,NaN
45,75895,19448,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,PENDING,...,327.750000,1,86.169998,18.264696,-66.037056,2.0,0.0,0.0,NaN,NaN
46,75894,19447,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,South Asia,Pacific Asia,PENDING,...,327.750000,1,130.580002,43.188240,-77.567062,3.0,0.0,0.0,NaN,NaN
47,75893,19446,smart watch,sporting goods,Fitness,327.750000,http://images.acmesports.sports/Smart+watch,Eastern Asia,Pacific Asia,PROCESSING,...,327.750000,1,0.000000,32.753685,-96.865540,0.0,0.0,0.0,NaN,NaN
48,28744,9083,perfect fitness perfect rip deck,cleats,Apparel,59.990002,http://images.acmesports.sports/Perfect+Fitnes...,South Asia,Pacific Asia,PENDING_PAYMENT,...,119.980003,2,-30.750000,18.380119,-66.183128,3.0,27878.0,2773.0,Sep,21.0
49,45461,4741,under armour girls' toddler spine surge runni,shop by sport,Golf,39.990002,http://images.acmesports.sports/Under+Armour+G...,West Asia,Pacific Asia,PENDING_PAYMENT,...,79.980003,2,-122.730003,18.235573,-66.370613,0.0,12511.0,2273.0,Sep,20.0

In [55]:
merged_df.to_parquet(
    CLEAN_OUTPUT_DIR / 'supply_chain.parquet',
    index=False
)

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [54]:
merged_df.to_parquet(
    f" '{CLEAN_OUTPUT_DIR}/supply_chain.parquet",
    index=False
)

OSError: Cannot save file into a non-existent directory: ' '../data/raw/product_department.csv'

In [ ]:
merged_df.to_csv(
    f"{CLEAN_OUTPUT_DIR}/merged_df.csv",
    index=False
)

FINAL GRAPH SCHEMA

NODES:-    
    
Customer
    
Order
    
Product
    
Category
    
Department
    
Region
    
Market
    
Payment

Relationships

Customer ──PLACED──> Order

Order ──CONTAINS──> Product

Product ──BELONGS_TO──> Category

Product ──PART_OF──> Department

Order ──SHIPPED_TO──> Region

Order ──IN_MARKET──> Market

Order ──PAID_VIA──> Payment

In [ ]:
merged_df[[
    "customer_id"
]].drop_duplicates().to_csv(f"{CLEAN_OUTPUT_DIR}/customers.csv", index=False)

In [ ]:
merged_df[[
    "order_id", "Shipping Mode", "Order Region", "Order Status", "delay"
]].drop_duplicates().to_csv(f"{CLEAN_OUTPUT_DIR}/orders.csv", index=False)

In [ ]:
merged_df[[
    "product_name", "category", "department",
    "Product Price", "product_image",
    "view_count", "unique_users",
    "peak_month", "peak_hour"
]].drop_duplicates().to_csv(f"{CLEAN_OUTPUT_DIR}/products.csv", index=False)

In [ ]:
merged_df[["category"]].drop_duplicates() \
    .to_csv(f"{CLEAN_OUTPUT_DIR}/categories.csv", index=False)

In [ ]:
merged_df[["department"]].drop_duplicates() \
    .to_csv(f"{CLEAN_OUTPUT_DIR}/departments.csv", index=False)

In [ ]:
merged_df[["Order Region"]].drop_duplicates() \
    .to_csv(f"{CLEAN_OUTPUT_DIR}/regions.csv", index=False)

In [ ]:
merged_df[["Market"]].drop_duplicates() \
    .to_csv(f"{CLEAN_OUTPUT_DIR}/markets.csv", index=False)

In [ ]:
payment_df = con.sql(f"""
SELECT DISTINCT Type AS payment_type
FROM read_csv_auto(
    {RAW_SUPPLY_CHAIN_CSV},
    ignore_errors=true
)
""").df()

payment_df.to_csv(f"{CLEAN_OUTPUT_DIR}/payments.csv", index=False)

In [ ]:
#Create relationship CSV's

BASE_PATH = CLEAN_OUTPUT_DIR

merged_df[["customer_id", "order_id"]] \
    .to_csv(f"{BASE_PATH}/customer_order.csv", index=False)

merged_df[["order_id", "product_name"]] \
    .to_csv(f"{BASE_PATH}/order_product.csv", index=False)

merged_df[["product_name", "category"]] \
    .drop_duplicates() \
    .to_csv(f"{BASE_PATH}/product_category.csv", index=False)

merged_df[["product_name", "department"]] \
    .drop_duplicates() \
    .to_csv(f"{BASE_PATH}/product_department.csv", index=False)

merged_df[["order_id", "Order Region"]] \
    .to_csv(f"{BASE_PATH}/order_region.csv", index=False)

merged_df[["order_id", "Market"]] \
    .to_csv(f"{BASE_PATH}/order_market.csv", index=False)